import type { SearchResult } from "./types";
import browserPreviewApplicationIcon from "../../src-tauri/icons/64x64.png?inline";

/**
 * Browser QA cannot call the native Windows Shell service. This fixture uses
 * iHub's own packaged raster icon and enters through the same strict PNG data
 * URL map as a real `get_system_icons` response, so browser validation covers
 * the renderer boundary without pretending to exercise Shell extraction.
 */
export const browserPreviewSystemIcons: Record<string, string> = {
  "preview-application-ihub": browserPreviewApplicationIcon,
};

export const mockResults: SearchResult[] = [
  {
    id: "preview-application-ihub",
    name: "iHub",
    kind: "application",
    score: 0.99,
    metadata: "应用图标渲染预览 · 原生宿主在桌面端提供",
    path: "C:\\Program Files\\iHub\\ihub.exe",
    modifiedAt: "2026-07-30T19:08:21+08:00",
    sizeBytes: 8_482_816,
  },
  {
    id: "welcome",
    name: "Welcome to iHub",
    kind: "command",
    score: 1,
    metadata: "Start indexing your local workspace",
    commandId: "ihub.index.default",
  },
  {
    id: "preview-file-app",
    name: "App.tsx",
    kind: "file",
    score: 0.98,
    metadata: "TypeScript · 当前工作区",
    path: "D:\\Code\\neko233-Projects\\ihub\\src\\App.tsx",
    modifiedAt: "2026-07-30T18:42:10+08:00",
    sizeBytes: 146_820,
  },
  {
    id: "preview-folder-plugins",
    name: "plugins",
    kind: "folder",
    score: 0.96,
    metadata: "插件 catalog 与官方模板",
    path: "D:\\Code\\neko233-Projects\\ihub\\plugins",
    modifiedAt: "2026-07-29T22:16:05+08:00",
  },
  {
    id: "preview-file-design",
    name: "DESIGN.md",
    kind: "file",
    score: 0.94,
    metadata: "iHub 交互设计说明",
    path: "D:\\Code\\neko233-Projects\\ihub\\docs\\DESIGN.md",
    modifiedAt: "2026-07-28T13:26:44+08:00",
    sizeBytes: 18_432,
  },
  {
    id: "preview-file-json",
    name: "package.json",
    kind: "file",
    score: 0.92,
    metadata: "JSON 配置文件",
    path: "D:\\Code\\neko233-Projects\\ihub\\package.json",
    modifiedAt: "2026-07-30T17:58:11+08:00",
    sizeBytes: 1_274,
  },
  {
    id: "preview-file-pdf",
    name: "iHub-product-spec.pdf",
    kind: "file",
    score: 0.9,
    metadata: "PDF 文档",
    path: "D:\\Documents\\iHub-product-spec.pdf",
    modifiedAt: "2026-07-27T11:02:54+08:00",
    sizeBytes: 2_840_576,
  },
  {
    id: "preview-file-image",
    name: "launcher-reference.png",
    kind: "file",
    score: 0.88,
    metadata: "PNG 图片",
    path: "D:\\Pictures\\launcher-reference.png",
    modifiedAt: "2026-07-26T09:47:36+08:00",
    sizeBytes: 486_390,
  },
  {
    id: "preview-file-video",
    name: "screen-recording.mp4",
    kind: "file",
    score: 0.86,
    metadata: "MP4 视频",
    path: "D:\\Videos\\screen-recording.mp4",
    modifiedAt: "2026-07-25T21:15:08+08:00",
    sizeBytes: 45_684_224,
  },
  {
    id: "preview-file-excel",
    name: "project-plan.xlsx",
    kind: "file",
    score: 0.84,
    metadata: "Excel 工作簿",
    path: "D:\\Documents\\project-plan.xlsx",
    modifiedAt: "2026-07-24T15:31:19+08:00",
    sizeBytes: 238_592,
  },
  {
    id: "preview-file-archive",
    name: "release-assets.zip",
    kind: "file",
    score: 0.82,
    metadata: "ZIP 压缩文件",
    path: "D:\\Downloads\\release-assets.zip",
    modifiedAt: "2026-07-23T08:05:42+08:00",
    sizeBytes: 12_984_320,
  },
  {
    id: "preview-file-audio",
    name: "launch-theme.flac",
    kind: "file",
    score: 0.8,
    metadata: "FLAC 音频",
    path: "D:\\Audio\\launch-theme.flac",
    modifiedAt: "2026-07-22T19:48:13+08:00",
    sizeBytes: 31_457_280,
  },
  {
    id: "preview-file-audio-opus",
    name: "launcher-chime.opus",
    kind: "file",
    score: 0.79,
    metadata: "Opus 音频",
    path: "D:\\Audio\\launcher-chime.opus",
    modifiedAt: "2026-07-22T18:40:02+08:00",
    sizeBytes: 2_621_440,
  },
  {
    id: "preview-file-3d",
    name: "mascot.glb",
    kind: "file",
    score: 0.78,
    metadata: "glTF 二进制 3D 模型",
    path: "D:\\Models\\mascot.glb",
    modifiedAt: "2026-07-21T14:23:11+08:00",
    sizeBytes: 7_602_176,
  },
  {
    id: "preview-file-3d-vrm",
    name: "assistant-avatar.vrm",
    kind: "file",
    score: 0.77,
    metadata: "VRM 角色模型",
    path: "D:\\Models\\assistant-avatar.vrm",
    modifiedAt: "2026-07-21T12:17:03+08:00",
    sizeBytes: 11_534_336,
  },
  {
    id: "preview-file-ebook",
    name: "iHub-handbook.epub",
    kind: "file",
    score: 0.76,
    metadata: "EPUB 电子书",
    path: "D:\\Books\\iHub-handbook.epub",
    modifiedAt: "2026-07-20T10:15:00+08:00",
    sizeBytes: 4_718_592,
  },
  {
    id: "preview-file-design-source",
    name: "launcher-mockup.psd",
    kind: "file",
    score: 0.74,
    metadata: "Photoshop 设计源文件",
    path: "D:\\Design\\launcher-mockup.psd",
    modifiedAt: "2026-07-19T17:32:40+08:00",
    sizeBytes: 84_934_656,
  },
  {
    id: "preview-file-font",
    name: "iHub-Sans.otf",
    kind: "file",
    score: 0.72,
    metadata: "OpenType 字体",
    path: "D:\\Fonts\\iHub-Sans.otf",
    modifiedAt: "2026-07-18T08:04:12+08:00",
    sizeBytes: 642_048,
  },
  {
    id: "preview-file-database",
    name: "catalog.sqlite",
    kind: "file",
    score: 0.7,
    metadata: "SQLite 数据库",
    path: "D:\\Data\\catalog.sqlite",
    modifiedAt: "2026-07-17T22:11:03+08:00",
    sizeBytes: 10_485_760,
  },
  {
    id: "preview-file-installer",
    name: "iHub-latest.msi",
    kind: "file",
    score: 0.68,
    metadata: "Windows Installer 安装包",
    path: "D:\\Downloads\\iHub-latest.msi",
    modifiedAt: "2026-07-16T12:42:26+08:00",
    sizeBytes: 52_428_800,
  },
];
