mod app;
mod background_process;
mod builtin_tools;
mod clipboard_access;
mod clipboard_history;
mod cloud_credentials;
mod cloud_drive;
mod detached_plugin_window;
mod host_log;
mod indexer;
mod launcher_hotkey;
mod launcher_shortcuts;
mod models;
mod native_color_picker;
mod native_icons;
mod native_screenshot;
mod ntfs_usn;
mod plugin_artwork;
mod plugin_asset_server;
mod plugin_settings;
mod plugin_shortcuts;
mod plugins;
mod project_template;
mod super_panel;
pub mod system_open;
mod window_management;

pub use app::run;
